export const downloadTraductions = {
    en: {
        downloadBul: 'Télécharger le bulletin',
        com: 'Compétences',
        subCom: 'Sous compétences',
        unit: 'Unité d\'apprentissage',
        eval: 'Evaluations',
        over: 'Sur',
        notes: 'Notes',
        noCom: 'Aucune competence',
        total: 'Total',
        help: 'COTES : NA = Non Acquis, ECA = En Cours d’Acquisition, A = Acquis, A+ = Expert',
        totalPoints: 'Total des points',
        cote: 'Côtes',
        classConseil: 'Conseil de classe',
        average: 'Moyenne',
        avert: 'Avertissement conduite',
        yes: 'Oui',
        no: 'Non',
        encou: 'Encouragement',
        rank: 'Rang',
        worlAvertissement: 'Avertissement travail',
        firstAverage: 'Moyenne du premier',
        lastAverage: 'Moyenne du dernier',
        honorRoll: 'Tableau d\'honneur',
        observation: 'Observation de l\'enseignant',
        visa: 'Visa du parent',
        chefVisa: 'Visa du chef d\'établissement',
        effort: 'Des efforts s\'imposent en :',
        class: 'Classe',
        teacher: 'Enseignant',
        sex: 'Sexe',
        birthday: 'Date de naissance',
        nameAndSubname: 'Noms et Prénoms',
        evalB: 'BULLETIN D\'EVALUATION'
    },
    fr: {
        downloadBul: 'Télécharger le bulletin',
        com: 'Compétences',
        subCom: 'Sous compétences',
        unit: 'Unité d\'apprentissage',
        eval: 'Evaluations',
        over: 'Sur',
        notes: 'Notes',
        noCom: 'Aucune competence',
        total: 'Total',
        help: 'COTES : NA = Non Acquis, ECA = En Cours d’Acquisition, A = Acquis, A+ = Expert',
        totalPoints: 'Total des points',
        cote: 'Côtes',
        classConseil: 'Conseil de classe',
        average: 'Moyenne',
        avert: 'Avertissement conduite',
        yes: 'Oui',
        no: 'Non',
        encou: 'Encouragement',
        rank: 'Rang',
        worlAvertissement: 'Avertissement travail',
        firstAverage: 'Moyenne du premier',
        lastAverage: 'Moyenne du dernier',
        honorRoll: 'Tableau d\'honneur',
        observation: 'Observation de l\'enseignant',
        visa: 'Visa du parent',
        chefVisa: 'Visa du chef d\'établissement',
        effort: 'Des efforts s\'imposent en :',
        class: 'Classe',
        teacher: 'Enseignant',
        sex: 'Sexe',
        birthday: 'Date de naissance',
        nameAndSubname: 'Noms et Prénoms',
        evalB: 'BULLETIN D\'EVALUATION',
    }
}