export const classTraductions = {
    en: {
        add_class: 'Ajouter une classe',
        className: 'Nom de la classe',
        classLevel: 'Niveau de la classe',
        section: 'Section',
        selectSection: '--- Selectionner la section ----',
        fr: 'Francophone',
        en: 'Anglophone',
        mat: 'Maternelle',
        level: 'Niveau',
        close: 'Fermer (Annuler)',
        save: 'Enregistrer',
        saving: 'Enregistrement...',
        class: 'Classe',
        visite: 'Visiter',
        delete: 'Supprimer',
        deleting: 'Suppression',
        nohaveclass: 'Aucune classe pour l\'instant',
        doyou: 'Voulez-vous en',
        add: ' ajouter ?',
        edit: 'Editer ',
        editClass: 'Editer une classe'
    },
    fr: {
        add_class: 'Ajouter une classe',
        className: 'Nom de la classe',
        classLevel: 'Niveau de la classe',
        section: 'Section',
        selectSection: '--- Selectionner la section ----',
        fr: 'Francophone',
        en: 'Anglophone',
        mat: 'Maternelle',
        level: 'Niveau',
        close: 'Fermer (Annuler)',
        save: 'Enregistrer',
        saving: 'Enregistrement...',
        class: 'Classe',
        visite: 'Visiter',
        delete: 'Supprimer',
        deleting: 'Suppression',
        nohaveclass: 'Aucune classe pour l\'instant',
        doyou: 'Voulez-vous en',
        add: ' ajouter ?',
        edit: 'Editer ',
        editClass: 'Editer une classe'
    }
}