export const comTraductions = {
    en: {
        addCom: 'Ajouter une compétence',
        comName: 'Nom de la compétence',
        section: 'Section',
        selectSection: '--- Selectionner la section ----',
        fr: 'Francophone',
        en: 'Anglophone',
        mat: 'Maternelle',
        level: 'Niveau',
        close: 'Fermer (Annuler)',
        save: 'Enregistrer',
        saving: 'Enregistrement...',
        com: 'Compétence',
        visite: 'Visiter',
        delete: 'Supprimer',
        deleting: 'Suppression',
        nohavecom: 'Aucune compétence pour l\'instant',
        doyou: 'Voulez-vous en',
        add: ' ajouter ?',
        edit: 'Editer ',
        name: 'Nom',
        action: 'Actions',
        editCom: 'Editer une competence'
    },
    fr: {
        addCom: 'Ajouter une compétence',
        comName: 'Nom de la compétence',
        section: 'Section',
        selectSection: '--- Selectionner la section ----',
        fr: 'Francophone',
        en: 'Anglophone',
        mat: 'Maternelle',
        level: 'Niveau',
        close: 'Fermer (Annuler)',
        save: 'Enregistrer',
        saving: 'Enregistrement...',
        com: 'Compétence',
        visite: 'Visiter',
        delete: 'Supprimer',
        deleting: 'Suppression',
        nohavecom: 'Aucune compétence pour l\'instant',
        doyou: 'Voulez-vous en',
        add: ' ajouter ?',
        edit: 'Editer ',
        name: 'Nom',
        action: 'Actions',
        editCom: 'Editer une competence'
    }
}