export const domainsTraductions = {
    en: {
        addDomain: 'Ajouter un domaine',
        section: 'Section',
        name: 'Nom',
        domainName: 'Nom du domaine',
        action: 'Actions',
        activities: 'Activités',
        seeActivities: 'Voir les activités',
        edit: 'Editer',
        saving: 'Enregistrement...',
        save: 'Enregistrer',
        close: 'Fermer (Annuler)',
        noDomain: 'Aucun domaine pour l\'instant.',
        doYou: 'Voulez-vous en',
        add: 'ajouter ?',
        editDomain: 'Editer un domaine',
        nber: 'Nombre d\'appréciations',
        addActivitie: 'Ajouter une activité',
        noAct: 'Aucune activité pour l\'instant',
        actDomain: 'Activités du domaine : ',
        activitieName: 'Nom de l\'activité',
    },
    fr: {
        addDomain: 'Ajouter un domaine',
        section: 'Section',
        name: 'Nom',
        action: 'Actions',
        activities: 'Activités',
        domainName: 'Nom du domaine',
        seeActivities: 'Voir les activités',
        edit: 'Editer',
        saving: 'Enregistrement...',
        save: 'Enregistrer',
        close: 'Fermer (Annuler)',
        noDomain: 'Aucun domaine pour l\'instant.',
        doYou: 'Voulez-vous en',
        add: 'ajouter ?',
        editDomain: 'Editer un domaine',
        nber: 'Nombre d\'appréciations',
        addActivitie: 'Ajouter une activité',
        noAct: 'Aucune activité pour l\'instant',
        actDomain: 'Activités du domaine : ',
        activitieName: 'Nom de l\'activité',
    }
}