export const sectionTraductions = {
    en: {
        addSection: 'Ajouter une section',
        editdSection: 'Ajouter une section',
        secName: 'Nom du section',
        type: 'Type de la section',
        addSeq: 'Veuillez ajouter des sequences pour continuer',
        selectSeq: 'Selectionner les séquences',
        close: 'Fermer (Annuler)',
        save: 'Enregistrer',
        visite: 'Visiter',
        saving: 'Enregist :rement...',
        name: 'Nom :',
        action: 'Action :s',
        noSection: 'Aucune section !',
        seeClass: 'Visiter',
        delete: 'Supprimer',
        deleting: 'Suppression...',
        edit: 'Editer',
        t: 'Type :',
    },
    fr: {
        addSection: 'Ajouter une section',
        editdSection: 'Ajouter une section',
        secName: 'Nom du section',
        type: 'Type de la section',
        addSeq: 'Veuillez ajouter des sequences pour continuer',
        selectSeq: 'Selectionner les séquences',
        close: 'Fermer (Annuler)',
        save: 'Enregistrer',
        visite: 'Visiter',
        saving: 'Enregistrement...',
        name: 'Nom :',
        action: 'Actions',
        t: 'Type :',
        noSection: 'Aucune section !',
        seeClass: 'Visiter',
        delete: 'Supprimer',
        deleting: 'Suppression...',
        edit: 'Editer',
    }
}