export const sequenceTraductions = {
    en: {
        addSeq: 'Ajouter une séquence',
        editSeq: 'Editer une séquence',
        seqName: 'Nom de la séquence',
        section: 'Section',
        selectSection: '--- Selectionner la section ----',
        fr: 'Francophone',
        en: 'Anglophone',
        mat: 'Maternelle',
        close: 'Fermer (Annuler)',
        save: 'Enregistrer',
        saving: 'Enregistrement...',
        seq: 'Séquence',
        delete: 'Supprimer',
        deleting: 'Suppression',
        nohavecom: 'Aucune compétence pour l\'instant',
        doyou: 'Voulez-vous en',
        add: ' ajouter ?',
        edit: 'Editer ',
        noSeq: 'Aucune sequence effectuee pour l\'instant. Attendez que l\'admin en cree.',
        enterData: 'Entrer les données',
        name: 'Nom',
        action: 'Actions',
        editCom: 'Editer une competence',
        competence: 'Compentece',
        order: 'Classer',
        noCom: 'Aucune competence',
        essential: 'Essentiel',
        total: 'Total',
        average: 'Moyenne',
        totalOfPoints: 'Total des points',
        rank: 'Rang',
        seeBul: 'Voir le bulletin',
        noStudent: 'Aucun élève dans cette classe',
        downloadBul: 'Télécharger le bulletin',
        downloadBuls: 'Télécharger le bulletins',
        importNotes: 'Importer les notes',
    },
    fr: {
        addSeq: 'Ajouter une séquence',
        editSeq: 'Editer une séquence',
        seqName: 'Nom de la séquence',
        section: 'Section',
        selectSection: '--- Selectionner la section ----',
        fr: 'Francophone',
        en: 'Anglophone',
        mat: 'Maternelle',
        close: 'Fermer (Annuler)',
        save: 'Enregistrer',
        saving: 'Enregistrement...',
        seq: 'Séquence',
        delete: 'Supprimer',
        deleting: 'Suppression',
        nohavecom: 'Aucune compétence pour l\'instant',
        doyou: 'Voulez-vous en',
        add: ' ajouter ?',
        edit: 'Editer ',
        noSeq: 'Aucune sequence effectuee pour l\'instant. Attendez que l\'admin en cree.',
        enterData: 'Entrer les données',
        name: 'Nom',
        action: 'Actions',
        editCom: 'Editer une competence',
        competence: 'Compentece',
        downloadBuls: 'Télécharger les bulletins',
        order: 'Classer',
        noCom: 'Aucune competence',
        essential: 'Essentiel',
        total: 'Total',
        average: 'Moyenne',
        totalOfPoints: 'Total des points',
        rank: 'Rang',
        seeBul: 'Voir le bulletin',
        noStudent: 'Aucun élève dans cette classe',
        downloadBul: 'Télécharger le bulletin',
        importNotes: 'Importer les notes',
    }
}