export const subjectTraductions = {
    en: {
        addSubject: 'Ajouter une matière',
        subjectName: 'Nom de la matière',
        section: 'Section',
        selectSection: '--- Selectionner la section ----',
        fr: 'Francophone',
        en: 'Anglophone',
        mat: 'Maternelle',
        slug: 'Slug',
        slugName: 'Slug de la matière',
        type: 'Type',
        close: 'Fermer (Annuler)',
        save: 'Enregistrer',
        saving: 'Enregistrement...',
        subject: 'Matière',
        over: 'Sur',
        visite: 'Visiter',
        delete: 'Supprimer',
        deleting: 'Suppression',
        nohavesubject: 'Aucune matière pour l\'instant',
        doyou: 'Voulez-vous en',
        add: ' ajouter ?',
        edit: 'Editer ',
        selectCompetence: '--- Sélectionner la compétence ---',
        name: 'Nom',
        action: 'Actions',
        editSubject: 'Editer une matière',
        competence: 'Competence',
        nohavesbject: 'Aucune sous competence pour cette competence pour le moment. ',
        oral: 'Orale',
        ecrit: 'Ecrit',
        subjectOver: 'Total de la matiere',
        savoirEtre: 'Savoir Être',
        pratic: 'Pratique',
        addSubCom: 'Ajouter une sous competence',
        select: 'Sélectionné',
        addCom: 'Veuilez ajouter des competences pour continuer',
        subName: 'Nom de la sous compétence',
    },
    fr: {
        addSubject: 'Ajouter une matière',
        subjectName: 'Nom de la matière',
        section: 'Section',
        selectSection: '--- Selectionner la section ----',
        addSubCom: 'Ajouter une sous competence',
        fr: 'Francophone',
        en: 'Anglophone',
        mat: 'Maternelle',
        slug: 'Slug',
        slugName: 'Slug de la matière',
        type: 'Type',
        close: 'Fermer (Annuler)',
        save: 'Enregistrer',
        saving: 'Enregistrement...',
        nohavesbject: 'Aucune sous competence pour cette competence pour le moment. ',
        subject: 'Matière',
        visite: 'Visiter',
        subjectOver: 'Total de la matiere',
        delete: 'Supprimer',
        deleting: 'Suppression',
        nohavesubject: 'Aucune matière pour l\'instant',
        doyou: 'Voulez-vous en',
        add: ' ajouter ?',
        edit: 'Editer ',
        selectCompetence: '--- Sélectionner la compétence ---',
        name: 'Nom',
        action: 'Actions',
        editSubject: 'Editer une matière',
        competence: 'Compentece',
        over: 'Sur',
        oral: 'Orale',
        ecrit: 'Ecrit',
        savoirEtre: 'Savoir Être',
        pratic: 'Pratique',
        select: 'Sélectionné',
        addCom: 'Veuilez ajouter des competences pour continuer',
        subName: 'Nom de la sous compétence',
    }
}