export const teacherTraductions = {
    en: {
        addTeacher: 'Ajouter un enseignant',
        editTeacher: 'Editer un enseignant',
        teacherName: 'Nom de l\'enseignagnt :',
        teacherSubname: 'Prénom de l\'ensignant :',
        teacherClassname: 'Classe de l\'enseignant',
        noClass: 'Veuillez créer une classe pour continuer :',
        selectClass: 'Sélectionnez une classe :',
        importTeacher: 'Importer les enseignant',
        seeMdp: 'Voir le mdp',
        generateNewMdp: 'Générer les mdp',
        downloadTeacherMdp: 'Telecharger les mots de passe.',
        loading: 'En cours...',
        number: 'Numéro de téléphone de l\'enseignant :',
        birthday: 'Date de naissance de l\'enseignant :',
        close: 'Fermer (Annuler)',
        name: 'Nom',
        sex: 'Sex de l\'enseignant',
        subname: 'Prenom',
        edit: 'Editer',
        class: 'Classe',
        section: 'Section',
        mr: 'Matr.',
        delete: 'Supprimer',
        mat: 'Maternelle',
        fr: 'Francophone',
        en: 'Anglogphone',
        deleting: 'Suppression...',
        noTeacher: 'Aucun enseignant pour l\'instant',
        doYou: 'Voulez-vous',
        add: 'ajouter ?',
        save: 'Enregistrer',
        saving: 'Enregistrement...',
        selectSex: '--- Selectionner le sexe de l\'enseignant ----',
        m: 'Masculin',
        f: 'Féminin',
    },
    fr: {
        addTeacher: 'Ajouter un enseignant',
        editTeacher: 'Editer un enseignant',
        teacherName: 'Nom de l\'enseignagnt :',
        teacherSubname: 'Prénom de l\'ensignant :',
        teacherClassname: 'Classe de l\'enseignant',
        noClass: 'Veuillez créer une classe pour continuer :',
        selectClass: 'Sélectionnez une classe :',
        importTeacher: 'Importer les enseignant',
        seeMdp: 'Voir le mdp',
        generateNewMdp: 'Générer les mdp',
        downloadTeacherMdp: 'Telecharger les mots de passe.',
        loading: 'En cours...',
        number: 'Numéro de téléphone de l\'enseignant :',
        birthday: 'Date de naissance de l\'enseignant :',
        close: 'Fermer (Annuler)',
        name: 'Nom',
        sex: 'Sex de l\'enseignant',
        subname: 'Prenom',
        edit: 'Editer',
        class: 'Classe',
        section: 'Section',
        mr: 'Matr.',
        delete: 'Supprimer',
        mat: 'Maternelle',
        fr: 'Francophone',
        en: 'Anglogphone',
        deleting: 'Suppression...',
        noTeacher: 'Aucun enseignant pour l\'instant',
        doYou: 'Voulez-vous',
        add: 'ajouter ?',
        save: 'Enregistrer',
        saving: 'Enregistrement...',
        selectSex: '--- Selectionner le sexe de l\'enseignant ----',
        m: 'Masculin',
        f: 'Féminin',
    }
}