export const trimTraductions = {
    en: {
        addTrim: 'Ajouter une trimestre',
        trimName: 'Nom du trimestre',
        addSeq: 'Veuillez ajouter des sequences pour continuer',
        selectSeq: 'Selectionner les séquences',
        close: 'Fermer (Annuler)',
        save: 'Enregistrer',
        saving: 'Enregistrement...',
        trim: 'Trimestre',
        seeData: 'Voir les données',
        delete: 'Supprimer',
        deleting: 'Suppression',
        nohavetrim: 'Aucun trimestre effectué pour l\'instant! Attendez que l\'admin en rajoute.',
        name: 'Nom',
        action: 'Actions',
        competence: 'Compentece',
        downloadBuls: 'Télécharger les bulletins',
        order: 'Classer',
        noCom: 'Aucune competence',
        essential: 'Essentiel',
        total: 'Total',
        average: 'Moyenne',
        totalOfPoints: 'Total des points',
        rank: 'Rang',
        seeBul: 'Voir le bulletin',
        noStudent: 'Aucun élève dans cette classe',
        downloadBul: 'Télécharger le bulletin',
    },
    fr: {
        addTrim: 'Ajouter une trimestre',
        trimName: 'Nom du trimestre',
        addSeq: 'Veuillez ajouter des sequences pour continuer',
        selectSeq: 'Selectionner les séquences',
        close: 'Fermer (Annuler)',
        save: 'Enregistrer',
        saving: 'Enregistrement...',
        trim: 'Trimestre',
        seeData: 'Voir les données',
        delete: 'Supprimer',
        deleting: 'Suppression',
        nohavetrim: 'Aucun trimestre effectué pour l\'instant! Attendez que l\'admin en rajoute.',
        name: 'Nom',
        action: 'Actions',
        competence: 'Compentece',
        downloadBuls: 'Télécharger les bulletins',
        order: 'Classer',
        noCom: 'Aucune competence',
        essential: 'Essentiel',
        total: 'Total',
        average: 'Moyenne',
        totalOfPoints: 'Total des points',
        rank: 'Rang',
        seeBul: 'Voir le bulletin',
        noStudent: 'Aucun élève dans cette classe',
        downloadBul: 'Télécharger le bulletin',
    }
}